### ISSUE TITLE
Set Up Filelink in Icedove not possible

### ISSUE THREAD

**Issue by quizilkend** [nextcloud/nextcloud-filelink#1]
### Steps to reproduce

1. Install the extension according to the README.md in this repository.
2. Add a filelink service and select nextcloud.

### Expected behaviour
The filelink setup window should appear.

### Actual behaviour
The filelink setup window contains an error message:
`
XML-Verarbeitungsfehler: Nicht definierte Entität Adresse: jar:file:///home/xxxx/.icedove/xxxxxxx.default/extensions/nextcloud-filelink@oparoz.com.xpi!/chrome/content/settings.xhtml Zeile Nr. 20, Spalte 27:
	<label for="displayName">&nextcloudSettings.provider;</label>
`

**Comment by oparoz** [comment]
Could you please try with a profile in English?
Did you use the file posted on the Mozilla website or did you create your own?

**Comment by quizilkend** [comment]
Okay.
Actually it works in a clean profile.
I use the language package provided by the debian repository.
Do you have an idea, what's the problem in my case?

**Comment by oparoz** [comment]
What happens if you use a clean profile and set it to German?

**Comment by guillaumev** [comment]
Closing this, feel free to reopen if needed.
