### ISSUE TITLE
Error while creating the account

### ISSUE THREAD

**Issue by dab0u** [nextcloud/nextcloud-filelink#14]
### Steps to reproduce

1. Try to create the account in Thunderbird (options -> attached files -> add
2. When I press OK, after a first "error message", now it won't say anything and do anything else (without error message)

### Expected behaviour
The goal was to creat an account to work with my personnal nextcloud server.

### Actual behaviour
An error occured and now, nothing happens when i try to submit the form.

**Thunderbird version :** Thunderbird 45.8.0
**Nextcloud version:** Nextcloud 11.0.2
**Updated from an older installation or fresh install:** fresh install

#### Thunderbird Log :
Horodatage : 18/04/2017 18:51:19
Erreur : NS_ERROR_MALFORMED_URI: Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService2.newURI]
Fichier source : resource://gre/components/nsLoginManagerPrompter.js
Ligne : 493

**Comment by oparoz** [comment]
Could you tell me how you installed the plugin?

**Comment by dab0u** [comment]
Download the github folder, make a zip with the src folder, rename the extension to .xpi and use the extension installer in thunderbird.

**Comment by dab0u** [comment]
I tried https://mydomain.com and that's all. Which would be the good address ? the webdav one ? without https ? But now, i can't have anymore error... :(

**Comment by oparoz** [comment]
That's the correct way to fill the form, but there is something Thunderbird doesn't like because it's complaining about a malformed URI.

**Comment by dab0u** [comment]
If you give me a way to private message you, i can send you the exact form i filled, if it can help you.

**Comment by dab0u** [comment]
Ho, it worked !! 
I had to create the folder manually BEFORE do it on thunderbird !
Thanks for your help. ;)

**Comment by oparoz** [comment]
Ah, cool.
It's in the readme, but ideally we should create the folder if it doesn't exist...

**Comment by jospoortvliet** [comment]
I will 'document' this on help.nextcloud.com as the search function makes sure ppl find this answer rather than ask it again ;-)

**Comment by jospoortvliet** [comment]
https://help.nextcloud.com/t/error-while-creating-the-account/11508
