### ISSUE TITLE
can't add a link in the mail.

### ISSUE THREAD

**Issue by dab0u** [nextcloud/nextcloud-filelink#17]
I succeeded in installing the extension, but when I try it can't add a link file in the mail i'm creating.
I create a new mail, add a file bigger than the limit I put in the extension's option (10Mo, my file il 17Mo), it seems to upload it (little green circle moving near the file's name) but at the end, it says "Impossible to upload -my file- to -my server" (in french).
I click on "ok" but nor link is added neither the file on my server.

I tried it with a smaller file with the "join a file" menu, but it does the same.

No error logged in the thunderbird console. Nothing in my nextcloud server too (apparently).

How can i see more ? 
(I owne my dedicated server, if it can help)

**Comment by bonanza123** [comment]
Are you sure that the folder you chose it to upload to (in the thunderbird settings) exists on the server?

**Comment by j-ed** [comment]
@dab0u You should check the content of the Nextcloud log file for further information. It helped me identifying a configuration problem as I first installed the add-on. Tested with Nextcloud 12.0.3 and Nextcloud for Filelink v1.7.

**Comment by guillaumev** [comment]
Closing this. Feel free to reopen if there is still an issue.
