### ISSUE TITLE
Not compatible with instances which use a sub-dir

### ISSUE THREAD

**Issue by koug44** [nextcloud/nextcloud-filelink#21]
Hey,

with the Git version of the plugin, adding an account on Thunderbird results in an error.

Server: Nextcloud 11.0.2
URL: https://myserver.org/owncloud

With the Error Console, I can see it's because the plugin is concatenating the URL and the port in a wrong way, resulting a in 404 error (screenshot below)

![capture du 2017-04-18 10-13-38](https://cloud.githubusercontent.com/assets/4643678/25304712/ac98ab38-273a-11e7-8f73-8104150c220a.png)

**Comment by oparoz** [comment]
Ah, interesting, thanks for the report.
It looks like we may have to introduce another field if we don't want to play with regular expressions.

**Comment by guillaumev** [comment]
This: https://github.com/nextcloud/nextcloud-filelink/commit/b87c0adb95ead574223d93ede18cc5ac0f89d5ac

should fix it. However, I wouldn't mind some more testing here, as I don't have an instance with a subdir available.

**Comment by koug44** [comment]
Works fine now. Looking forward to use it for real

**Comment by sebastian-orlowski** [comment]
The fix works for me, too, with Nextcloud 11.0.0, TB 52.2.1. Thanks!
