### ISSUE TITLE
Nextcloud not showing up in the provider dropdown

### ISSUE THREAD

**Issue by decibyte** [nextcloud/nextcloud-filelink#22]
### Steps to reproduce

1. Follow installation instructions in README.
1. Restart Thunderbird, go to the Add panel. In the dropdown, I only see existing providers. No Nextcloud.

If I install the extension from AMO, it shows up properly as "ownCloud/nextCloud".

### Desktop configuration

**Operating system**:

Ubuntu 17.04

**Thunderbird version:**

45.8.0

**Updated from an older installation or fresh install:**

What software is referred to here? If it's Thunderbird, it's managed by the package manager of Ubuntu. Not a fresh install.

**Comment by guillaumev** [comment]
@decibyte are you sure you don't have the extension installed 2 times, ie one from addons.mozilla.org and one from this git repository ?

**Comment by Kaor** [comment]
same problem here with version 1.5

**Comment by guillaumev** [comment]
@Kaor can you try reverting back to 1.4, then deleting the nextcloud provider from thunderbird, and then installing 1.5 again ? Let me know if this works, sorry for the inconvenience...

**Comment by Kaor** [comment]
thanks for your answer,
where can i find 1.4 version ?

**Comment by guillaumev** [comment]
Here: https://addons.mozilla.org/firefox/downloads/file/618765/owncloud_for_filelink-1.4-tb.xpi?src=devhub

**Comment by Kaor** [comment]
it works with 1.4 version, the configuration is here.
it's impossible for me to delete configuration, install version 1.5 and install new configuration on all my hosts,
too long and too complicated... sorry
We'll wait for new version who don't break configuration,
thanks

**Comment by j-ed** [comment]
I couldn't replicate this problem anymore with TB v52.3.0 (Win7) and Nextcloud for Filelink v1.7, everything works as expected.
