### ISSUE TITLE
unknown error on upload

### ISSUE THREAD

**Issue by ste7613** [nextcloud/nextcloud-filelink#23]
### Steps to reproduce

1. install & configure nextcloud-filelink 1.5 in thunderbird
2. write a mail, try to attach a big file, say "Use FileLink"
3. i got "unknown error"
4. in the nexcloud folder i see the attached file with an timestamp_prefix

### Expected behaviour
no errors

### Actual behaviour
it should just work

### Server configuration

**Operating system**: Debian 8.7

**Web server:** nginx 1.11.13

**Database:** mariadb 10.1.22

**PHP version:** 5.6.30+dfsg-0+deb8u1

**Nextcloud version:** 11.0.2.7

**Updated from an older installation or fresh install:** updated

**List of activated apps:**

<details>
<summary>App list</summary>
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.5.1
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
</details>

**The content of config/config.php:**

<details>
<summary>Config report</summary>
  'datadirectory' => '/var/www/owncloud',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => '...',
  'dbpassword' => '...',
  'installed' => true,
  'proxy' => 'my.proxy:3128',
  'forcessl' => true,
  'mail_from_address' => 'noreply',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'my.dom',
  'ldapIgnoreNamingRules' => false,
  'mail_smtppassword' => '',
  'loglevel' => 2,
  'default_language' => 'en',
  'theme' => '',
  'filesystem_check_changes' => '1',
  'maintenance' => false,
  'secret' => '...',
  'trashbin_retention_obligation' => 'auto, 14',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

#### Web server error log

<details>
<summary>Web server error log</summary>
empty
</details>

#### Cloud log

<details>
<summary>Nextcloud log</summary>
{"reqId":"U7TioQS5+sp6EXekZpeg","remoteAddr":"192.168.1.42","app":"no app in context","message":"Missing expected parameters in change user hook","level":2,"time":"2017-05-17T13:03:35+00:00","method":"PROPFIND","url":"\/remote.php\/webdav","user":"7F34B8CE-62DF-4E55-BC4B-79AB026440F7","version":"11.0.2.7"}
{"reqId":"\/WSQ0y3Jm9pDI4eOXLSZ","remoteAddr":"192.168.1.42","app":"no app in context","message":"Missing expected parameters in change user hook","level":2,"time":"2017-05-17T13:03:38+00:00","method":"PUT","url":"\/remote.php\/webdav\/temp\/1495026215819_Screen%20Shot%202016-07-12%20at%2013.33.44.png","user":"7F34B8CE-62DF-4E55-BC4B-79AB026440F7","version":"11.0.2.7"}
{"reqId":"\/WSQ0y3Jm9pDI4eOXLSZ","remoteAddr":"192.168.1.42","app":"no app in context","message":"Missing expected parameters in change user hook","level":2,"time":"2017-05-17T13:03:38+00:00","method":"PUT","url":"\/remote.php\/webdav\/temp\/1495026215819_Screen%20Shot%202016-07-12%20at%2013.33.44.png","user":"7F34B8CE-62DF-4E55-BC4B-79AB026440F7","version":"11.0.2.7"}
{"reqId":"b8Jbu7vV4YdtJgheoYEF","remoteAddr":"192.168.1.42","app":"no app in context","message":"Missing expected parameters in change user hook","level":2,"time":"2017-05-17T13:04:00+00:00","method":"GET","url":"\/ocs\/v1.php\/cloud\/user?format=json","user":"7F34B8CE-62DF-4E55-BC4B-79AB026440F7","version":"11.0.2.7"}
{"reqId":"b8Jbu7vV4YdtJgheoYEF","remoteAddr":"192.168.1.42","app":"no app in context","message":"Missing expected parameters in change user hook","level":2,"time":"2017-05-17T13:04:00+00:00","method":"GET","url":"\/ocs\/v1.php\/cloud\/user?format=json","user":"7F34B8CE-62DF-4E55-BC4B-79AB026440F7","version":"11.0.2.7"}
{"reqId":"DOEfAgRYMRFJrFHItQMx","remoteAddr":"192.168.1.42","app":"no app in context","message":"Missing expected parameters in change user hook","level":2,"time":"2017-05-17T13:04:02+00:00","method":"PROPFIND","url":"\/remote.php\/webdav","user":"7F34B8CE-62DF-4E55-BC4B-79AB026440F7","version":"11.0.2.7"}
{"reqId":"DOEfAgRYMRFJrFHItQMx","remoteAddr":"192.168.1.42","app":"no app in context","message":"Missing expected parameters in change user hook","level":2,"time":"2017-05-17T13:04:02+00:00","method":"PROPFIND","url":"\/remote.php\/webdav","user":"7F34B8CE-62DF-4E55-BC4B-79AB026440F7","version":"11.0.2.7"}
{"reqId":"o+TXPtk0PnVe6gP+6zi9","remoteAddr":"192.168.1.42","app":"no app in context","message":"Missing expected parameters in change user hook","level":2,"time":"2017-05-17T13:04:05+00:00","method":"PUT","url":"\/remote.php\/webdav\/temp\/1495026242814_Screen%20Shot%202016-07-12%20at%2013.33.44.png","user":"7F34B8CE-62DF-4E55-BC4B-79AB026440F7","version":"11.0.2.7"}
</details>

### Desktop configuration

**Operating system**: Ubuntu 16.04 LTS

**Thunderbird version:** 52.1.1 (64-Bit)

**Updated from an older installation or fresh install:** updated

#### Thunderbird Log

<details>
<summary>Thunderbird log</summary>
i can't find a log
</details>
 
![auswahl_313](https://cloud.githubusercontent.com/assets/20125314/26155716/6fbf1182-3b14-11e7-8ca2-7785eab2ba86.png)

**Comment by creopard** [comment]
Same here with Nextcloud 12 and Filelink 1.5, see also  https://github.com/nextcloud/nextcloud-filelink/issues/24
However the file gets uploaded properly in the remote "Mail-attachments" folder.
How can the "unknown error" be examined in Thunderbird?

**Comment by guillaumev** [comment]
This will be fixed in 1.6, or if you use the dev version of this repository, so closing this. Unfortunately, we are waiting for Mozilla to approve version 1.5 of this addon.
