### ISSUE TITLE
Unbekannter Fehler 

### ISSUE THREAD

**Issue by Django43** [nextcloud/nextcloud-filelink#24]
I have a problem with Nextcloud for Filelink.

My system:
Nextcloud: 12.0.0
Nextcloud runs on NAS-Server with Openmediavault 3.0.77
Certificate: Own certificate with LetsEncrypt
Thunderbird: 54.0b2
Operating system Win10
Install & configure nextcloud for filelink 1.5 in Thunderbird

I have little computer skills.

In Nextcloud, I created a separate path /mail before installing the addon.

In the installation mask I have specified as Provider "Nextcloud". I hope this is correct?

When attempting to send an email, Thunderbird correctly places the attachment in the created path on Nextcloud, but then the following error message appears:

An unknown error occurred while exchanging data with Nextcloud.

I've seen in "google" that this error has already occurred, but I have not managed to eliminate the error. I would be happy about a solution.

Django43

**Comment by creopard** [comment]
The change in PR #19 will fix this issue :)

**Comment by Django43** [comment]
Thank you for your response.

I have installed the "new" Version but i have already the same error. i got the message:

_An unknown error occurred while exchanging data with Nextcloud._

Please check one time more your solution.

Thank you very much.

Django43

**Comment by creopard** [comment]
The release here on Github is still version 1.5 which is not updated yet.
You have to edit the file "src/components/nsNextcloud.js" yourself or take the file from the master branch directly: https://github.com/nextcloud/nextcloud-filelink/blob/master/src/components/nsNextcloud.js and replace it in your xpi/zip addon.

**Comment by Django43** [comment]
Thank you for your reply.

Now I can say, the addon is okay.

Thank you very much. 

You can close the ticket.

Django43

**Comment by guillaumev** [comment]
Closing this.
