### ISSUE TITLE
Server URL requires scheme 

### ISSUE THREAD

**Issue by sualko** [nextcloud/nextcloud-filelink#29]
## Bug report
"Set up Account" button doesn't response if you enter a "plain" url without scheme (http/https).

### Steps to reproduce

1. Enter all desired settings (Provider, Server URL, Port number, Username, Storage path). Remove the protocol part of your url.
2. "Set up Account" button gets active
3. Click on button doesn't result in any action

### Expected behaviour
Set up should complete or an error message should pop up.

### Actual behaviour
Nothing

### Server configuration

**Nextcloud version:** 11

**Updated from an older installation or fresh install:** update

**Are you using encryption:** no

### Desktop configuration

**Operating system**: Ubuntu 17.04

**Thunderbird version:** 52.1.1

**Nextcloud Filelink version:** 1.0 from addon repo

#### Thunderbird Log

```
NS_ERROR_MALFORMED_URI: Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService2.newURI] nsLoginManagerPrompter.js:527
```

**Comment by guillaumev** [comment]
An error message should now pop up. Closing this, feel free to reopen if it's still not fixed on your side.
