### ISSUE TITLE
module update break configuration

### ISSUE THREAD

**Issue by Kaor** [nextcloud/nextcloud-filelink#35]
### Steps to reproduce

1. start thunderbird after updating filelink module

### Expected behaviour
work

### Actual behaviour
don't work, the configuration was deleted, like a new installation

### Desktop configuration

**Operating system**: Ubuntu 14.04

**Thunderbird version:** 52

**Updated from an older installation or fresh install:** updated

**Comment by guillaumev** [comment]
@Kaor see my comment in #22

**Comment by guillaumev** [comment]
Closing this for follow up in #22
