### ISSUE TITLE
Can't setup filelink after I deleted account to change passwords

### ISSUE THREAD

**Issue by lars-becker** [nextcloud/nextcloud-filelink#36]
## Bug report

I experienced problems since a few month with the filelink plugin since I switched to 2FA. Today I tried to investigate since I always got the error message "can't communicate with nextcloud" (or something like that; can't reproduce it because of the following error).

I found the following in the server logs:

```
46.59.163.252 - lars [28/Jul/2017:23:43:51 +0200] "PUT /remote.php/webdav/filelink/1501278230995_test.png HTTP/1.1" 201 1425 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Thunderbird/52.2.1 Lightning"
46.59.163.252 - - [28/Jul/2017:23:43:53 +0200] "POST /ocs/v1.php/apps/files_sharing/api/v1/shares?format=json HTTP/1.1" 401 1413 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Thunderbird/52.2.1 Lightning"
```

So the file was created (Status 201) but not the link (401). 

Since I was unable to solve the problem I deleted the plugin and the stored passwords (which were hard to find since the other plugins for CalDAV and CardDAV) and reset the entries under `mail.cloud_files.accounts.account1.*`. I reinstalled the plugin and tried to set it up again which fails with the message "Checking authorization" followed by an unspecific "An error occurred while setting up the account!"

Deleting the password from the password manager and resetting the above mentioned entries in the advanced config doesn't  help. 

Any ideas how to debug this one? I have no experience with the development of Firefox plugins.

### Server configuration

**Thunderbird**: 52.2.1 (64bit; current Archlinux package)
**Filelink Plugin**: 1.5 (current version from AMO)
Other Add-Ons like Cardbook and Lightning do work as expected.

And while I'm quite sure that the problem is with the plugin here the info about the server : 
**Operating system**: Ubuntu 16.04.2 LTS (Xenial Xerus)
**Web server:** Apache (2.4.18-2ubuntu3.4)
**Database:** : MySQL (5.7.19-0ubuntu0.16.04.1)
**PHP version:** PHP 7 (7.0+35ubuntu6)
**Nextcloud version:** 12.0.0
**Updated from an older installation or fresh install:** updated from an older installation (in many steps since 6.0)

#### Cloud log
Nothing relevant logged; only a few warnings and notices from other apps.

### Desktop configuration
**Operating system**: Archlinux
**Updated from an older installation or fresh install:** Updated of course... :-D 

#### Thunderbird Log
Nothing interessting in there but hundreds of lighning errors

**Comment by j-ed** [comment]
I'm using the a two factor authentication too with NC 12.0.3 and had to setup a **dedicated app password** for the add-on to get it working (Personal->Security->Create new app password). Additionally  you have to make sure that the **Allow file system access** option is ticked in the ...-menu of the app entry.

**Comment by guillaumev** [comment]
I believe @j-ed provided a solution here, so I'm closing this issue.
