### ISSUE TITLE
Thunderbird plugin v1.6 has wrong compatibility settings

### ISSUE THREAD

**Issue by GortiZ6** [nextcloud/nextcloud-filelink#40]
## Bug report
The plugin uploaded to Mozilla for version 1.6 has compatibility set for Thunderbird 17-45 while the current Thunderbird version is 52 and the plugin 1.5 has 17+ compatibility settings

### Steps to reproduce

1. Try to install Nextcloud-Filelink from Thunderbird 52 Add-on menu and the only available version is 1.5

### Expected behavior

1. Nextcloud-Filelink v1.6 available on the add-on repository for Thunderbird 17+

**Comment by GortiZ6** [comment]
@guillaumev, @oparoz could you please recompile and submit a new version? This should be a quick task for you and it's already 22 days since my issue... unfortunately I can't fix this by myself and all the effort put on V1.6 is useless if nobody can install it :(

**Comment by Judibet** [comment]
Hello,

I'm agree with @GortiZ6 because Nexcloud is avalaible for Thunderbird 52 but showed like not compatible.
You can check [this link](https://addons.mozilla.org/en-US/thunderbird/addon/nextcloud-filelink/) to test.

**Comment by guillaumev** [comment]
Ok version 1.7 has been submitted to addons.mozilla.org for review. It should appear soon hopefully... Sorry for the late reply on this...

**Comment by oparoz** [comment]
Just got the mail from Mozilla that it has been approved. Thanks @guillaumev

**Comment by GortiZ6** [comment]
I confirm that it's now available on Thunderbird. Thanks
