### ISSUE TITLE
Compatibility with Thunderbird 60.0

### ISSUE THREAD

**Issue by adi-dev** [nextcloud/nextcloud-filelink#55]
It's more a feature request than an issue at this moment because the tested version of Thunderbird is in beta state, 60.0 but I can see this will become a problem in the future. Thunderbird just refuses to use this add-on. Unless there is any other reason, can someone have a look at this?

**Comment by creopard** [comment]
Do you mean you can't select the nextcloud filelink in the dropdown any more, where "box.com" is the default option? Canit be related to the TB issue fixed here (scheduled for TB61):
https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1451280

**Comment by adi-dev** [comment]
The issue is that the TB doesn't allow to install (or activate) filelink extension as it's not compatibile with "this version of TB"
![screenshot1](https://user-images.githubusercontent.com/7880069/39965058-c9b14c0a-5689-11e8-9b21-aa6f55f78252.png)
![screenshot2](https://user-images.githubusercontent.com/7880069/39965057-c9963492-5689-11e8-8c09-b44047ea7108.png)

**Comment by TKaluza** [comment]
But you can just use the github version and install it manually. 
That should work

**Comment by adi-dev** [comment]
I tried that before, and again just now downloading latest copy from github, zip contents of src, rename the zip file to xpi extension and.. tb still refuses to install this. Any thoughts? Can I help in any way?

![screenshot-20180606](https://user-images.githubusercontent.com/7880069/41024408-0f4c350a-6967-11e8-9fca-e311b3f0e66b.png)

**Comment by creopard** [comment]
Installing it manually in TB 60 requires to edit the file "install.rdf" in the ZIP package from
`<em:maxVersion>57.*</em:maxVersion>`
to
`<em:maxVersion>60.*</em:maxVersion>`

(However I don't know if the addon still works with TB 60 or if there were any changes to the filelink functionality itself in TB 60.)

**Comment by adi-dev** [comment]
@creopard you right, it installed all right now but it wont let me set up a new account. I have removed the old one (as it existed in the config) and gone to re-create it. The button "Set up Account" on the "Set up Filelink" dialog box doesn't seem to work. It's enabled but it doesn't response on clicking.

**Comment by MontyZuma** [comment]
Had the problem with Set up Account, too. Got it fixed by using the config editor (https://support.mozilla.org/en-US/kb/config-editor): search for mail.cloud_files and reset all configuration for your nextcloud/owncloud account.

After that I was able to set up a new nextcloud account without problems.

**Comment by adi-dev** [comment]
Ok, tried once again, two errors:
```
TypeError: Cc['@mozilla.org/xmlextras/xmlhttprequest;1'] is undefined[Learn More]  nsNextcloud.js:438:7
```
```
NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "Cc['@mozilla.org/xmlextras/xmlhttprequest;1'] is undefined" {file: "jar:file:///C:/Users/XXXXXX/AppData/Roaming/Thunderbird/Profiles/XXXXXX.default/extensions/owncloud@viguierjust.com.xpi!/components/nsNextcloud.js" line: 438}]'[JavaScript Error: "Cc['@mozilla.org/xmlextras/xmlhttprequest;1'] is undefined" {file: "jar:file:///C:/Users/XXXXXX/AppData/Roaming/Thunderbird/Profiles/XXXXX.default/extensions/owncloud@viguierjust.com.xpi!/components/nsNextcloud.js" line: 438}]' when calling method: [nsIMsgCloudFileProvider::createExistingAccount]  cloudFileAccounts.js:106
	createAccount resource:///modules/cloudFileAccounts.js:106:9
	AAD_onOK chrome://messenger/content/cloudfile/addAccountDialog.js:224:20
	anonymous chrome://global/content/bindings/dialog.xml%20line%20407%20%3E%20Function:3:8
	_fireButtonEvent chrome://global/content/bindings/dialog.xml:408:28
	_doButtonCommand chrome://global/content/bindings/dialog.xml:376:28
	_handleButtonCommand chrome://global/content/bindings/dialog.xml:364:18
	CFA_addAccountDialog resource:///modules/cloudFileAccounts.js:188:5
	CFT_addCloudFileAccount chrome://messenger/content/preferences/applications.js:752:22
	doCommand chrome://messenger/content/preferences/applications.js:443:9
	doCommand chrome://messenger/content/preferences/applications.js:487:5
	goDoCommand chrome://global/content/globalOverlay.js:84:7
	oncommand chrome://messenger/content/preferences/preferences.xul:1:1
	openOptionsDialog chrome://messenger/content/mailCore.js:446:7
	oncommand chrome://messenger/content/messenger.xul:1:1
```

**Comment by bastien30** [comment]
Hello,

Any news regarding this add-on update ?

Thanks.
