### ISSUE TITLE
Unknown Error while uploading - no insert of text

### ISSUE THREAD

**Issue by jamfx** [nextcloud/nextcloud-filelink#56]
### Steps to reproduce

1. Attach a File in Thunderbird
2. Push button for "Upload with filelink"
3. See unknown error

### Expected behaviour
File uploaded without error, Text in E-Mail with instructions for Download

### Actual behaviour
There is shown an Errormessage "Unknown Error while uploading", **but**  the file is uplaoded to my Nextcloud. 

### Server configuration
**Operating system**: 
debian
**Web server:**
apache
**Database:**
mysql
**PHP version:**
7.1.3
**Nextcloud version:** (see admin page or version.php)
13.0.1
**Updated from an older installation or fresh install:**
Updated from an OwnCloud once up on a time in a galaxy far far away...
Nearly all standard apps. None extravagant.

**Are you using external storage, if yes which one:** local folder, smb share, sftp, etc.
no
**Are you using encryption:** yes/no
no

### Desktop configuration
**Operating system**:
Linux Mint 18.3 and Windows 10 latest release both on newset patchlevels
**Thunderbird version:**
52.7.0 64 Bit
**Updated from an older installation or fresh install:**
Updated

**Comment by jamfx** [comment]
I will check this with a harder Password. And will report here.

**Comment by splitt3r** [comment]
#31 seems to be related.

**Comment by jamfx** [comment]
So I can report back now:
YES: If you use a "better" Password (than I used before), FileLink works as expected. So please change the Error-Message to something more explicit or even better, don't accept a weak Password while configuring Nextcloud. That would help not to fall into this trap.
Best regards and thanks to @datavizzard for the hint!

For me: case closed.
JamFX

**Comment by datavizzard** [comment]
Maybe a developer could look at it and on #31 anyway because the part with the password is very tricky for basic users and its not easy to solve it.
