### ISSUE TITLE
Problems with Filelink for Nextcloud

### ISSUE THREAD

**Issue by ghwtb** [nextcloud/nextcloud-filelink#64]
@all

Ich habe leider ein Problem mit Filelink for Nextcloud.

Nachdem ich Thunderbird auf die Version 60.3.0 geuptatet habe, bekomme ich für das Addon Filelink for Nextcloud folgende Fehlermeldung:

Beim Hochladen von (Dateiname) trat ein Fehler auf. 

Tatsächlich wird jedoch die Datei in das vorgesehene Verzeichnis von Nextcloud upgeloaded, jedoch wird der Link in der Mail nicht erstellt.

Ich habe bereits auf die Version 1.8 von Filelink geupdatet.

Nextcloud habe ich in der Version 14.0.3 (beta).

Was mich nur irritiert ist, dass in der alten Thinderbird Version (52) und Filelink (1.7) alles funktionierte.

Es wäre super, wenn mir einer helfen könnte.

Vielen Dank im Voraus

@All

Unfortunately, I have a problem with Filelink for Nextcloud.

After I ripped Thunderbird to version 60.3.0, I get the following error message for the Filelink for Nextcloud addon:

Uploading (filename) failed.

In fact, however, the file is uploaded to the intended Nextcloud directory, but the link is not created in the mail.

I have already updated to version 1.8 of Filelink.

I have Nextcloud in version 14.0.3 (beta).

What irritates me is that in the old Thinderbird version (52) and Filelink (1.7) everything worked.

It would be great if someone could help me.

Thanks in advance

**Comment by alfredbuehler** [comment]
I have the same issue. With v1.7 everything works fine, v1.8 gives an authentication error. I'm on ownCloud,

**Comment by creopard** [comment]
Your problem(s) seems to be already mentioned at #43 
It could refer to the password policy, i.e. weak password used.

**Comment by alfredbuehler** [comment]
Thanks for the reference.
I dont know of any  password policy in effect.

**Comment by ghwtb** [comment]
@creopard 

Vielen Dank. Dein Hinweis war der richtige Treffer. Ich habe mein Passwort nunmehr auf 11 Zeichen erhöht .... und tatsächlich ..... es funktioniert.

In der Beschreibung sollte dieses Problem aufgenommen werden, damit andere Benutzer keine langwierigen Untersuchungen machen müssen.

Viele Grüße

@creopard 

Many Thanks. Your hint was the right match. I have now increased my password to 11 characters .... and indeed ..... it works.

This problem should be included in the description so that other users do not have to go through a lengthy investigation.

many Greetings
