### ISSUE TITLE
Can only select "Box-Account" no Nextcloud possible

### ISSUE THREAD

**Issue by kowjens** [nextcloud/nextcloud-filelink#70]
## Bug report
When I try to setup a second Nextcloud Account. It doesn't show any Service, only "Box"
### Steps to reproduce

1. Goto Setup -> Attachments (I've German, sorry if my translated Menus doesn't fit 100%)
2. Click Button "Add.."
3. here I can only select a new account via"Box"

### Expected behaviour

I should get a dialogue to add my nextcloud or any other service??
### Actual behaviour

only box available
### Server configuration
The issue comes from the plugin, so i'll avoid the server stuff
**Operating system**:
--
**Web server:**
--
**Database:**

**PHP version:**

**Nextcloud version:** (see admin page or version.php)

**Updated from an older installation or fresh install:**

**List of activated apps:**

<details>
<summary>App list</summary>

```
Paste the list of applications here
```

</details>

**The content of config/config.php:**

<details>
<summary>Config report</summary>

```
Paste the config here
```

</details>

**Are you using external storage, if yes which one:** local folder, smb share, sftp, etc.

**Are you using encryption:** yes/no

#### Web server error log

<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Cloud log

<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

### Desktop configuration

**Operating system**:

**Thunderbird version:**
52.9.1
**Updated from an older installation or fresh install:**
(since version 10 or 20 installed)
#### Thunderbird Log

<details>
<summary>Thunderbird log</summary>

```
Insert your browser log here
```

</details>
 
## Feature request

**User level**: Beginners, intermediate or advanced

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by manu-p** [comment]
Hi, same for me. 

Tbird 60.4.0 (64 bits) on Ubuntu 18.04.1 and Nextcloud for Filelink 1.8.

I can add that having an already set filelink on a nextcloud server, this is working. 
I just wanted/needed to set up another filelink to another nextcloud server and I don't find nextcloud in the list, only "box" is displayed. :-/

**Comment by alfredbuehler** [comment]
> Hi, same for me.
> 
> Tbird 60.4.0 (64 bits) on Ubuntu 18.04.1 and Nextcloud for Filelink 1.8.
> 
> I can add that having an already set filelink on a nextcloud server, this is working.
> I just wanted/needed to set up another filelink to another nextcloud server and I don't find nextcloud in the list, only "box" is displayed. :-/

Not sure, but I think this is by design. You can only add one connection for each category. 
See  issue #68

**Comment by manu-p** [comment]
@alfredbuehler thanks for the info and link, I might try to delete the existing one to check it out, but what if I still can't find any nextcloud possibility in the list for Filelink?...

**Comment by alfredbuehler** [comment]
In Thunderbird: _Edit -> Preferences -> Advanced -> Config Editor_.
Search for _mail.cloud_files.accounts_, and delete any unwanted account.

**Comment by manu-p** [comment]
Sorry, I may not have been clear @alfredbuehler. 
I'm not facing issues to delete a nextcloud filelink account, but fear I might not be able to create again a nextcloud account after deleting the one I had, according to this here issue.

**Comment by alfredbuehler** [comment]
OK I misunderstood, Sorry.

**Comment by kowjens** [comment]
Hi everybody,

thanks for your input.
I backuped my Thunderbird profile and tested after deleting the already set Nextcloud-Account ...
It works and shows box and Nextcloud to select :)

So it is related to  issue #68 (thx @alfredbuehler)

I'll close this as solved and hope that multiple accounts will be implemented in future ...

thanks everybody and nice weekend ..
