### ISSUE TITLE
Plan for this module ?

### ISSUE THREAD

**Issue by guillaumev** [nextcloud/nextcloud-filelink#8]
@oparoz Thank you for citing me in this code. I'm guessing this module is meant to be released in the Thunderbird ecosystem at some point. If you would like me to give you ownership of my module in Thunderbird so you can upload your module as a new version of mine, or would like me to mark my module as deprecated let me know, as I don't think it makes sense to have 2 competing "nextcloud for filelink" modules...

Feel free to get in touch with me: https://www.viguierjust.com

**Comment by oparoz** [comment]
@guillaumev - I'm going to contact you offline to decide what to do. I wanted to have a Nextcloud version and it didn't make sense to work in the ownCloud repo, so I created this one.
