### ISSUE TITLE
Add TB 68 support

### ISSUE THREAD

**Issue by johndoe7000** [nextcloud/nextcloud-filelink#80]
Hello,

please add Thunderbird 68.0 support.
There are also some nice pull requests in the pipe... "Add random password generation support for each upload" would be really nice.

**Comment by e-alfred** [comment]
@oparoz @guillaumev It would be great to revive this extension. Do you know which parts have to be fixed to make it work with Thunderbird 68?

**Comment by adhome1** [comment]
Yes please try a update. There are near none FileLink alternatives for 68.0
Perhaps this can help:
https://developer.thunderbird.net/add-ons/updates
At least a manifest.json is needed. Also other 68.0 FileLink addons can help to be analysed.

**Comment by guillaume-smo** [comment]
The WebDav filelink provider module works well with TB68 and NextCloud if it can help.

**Comment by e-alfred** [comment]
@guillaume-smo How did you set up the Webdav filelink provider?

**Comment by uku69** [comment]
@gulliaume-smo:
Yes, the upload to nextcloud is working fine with WebDAV. 
But: the link created couldn't be used at mail receivers. 
First a password is needed and second it's not possible to download the document :-O
If I upload a document manually to nextcloud and generate a link and add the link to the mail, the system works fine :-)

**Comment by thenamelessthing** [comment]
I agree with this request!

**Comment by guillaumev** [comment]
I created a PR here: https://github.com/nextcloud/nextcloud-filelink/pull/82 This is in a very early stage and for now, nothing works, but help will be greatly appreciated :-)

**Comment by ediazcomellas** [comment]
Will it help if I post a bounty for this?

**Comment by e-alfred** [comment]
@ediazcomellas I think posting a bounty is always a good incentive.

**Comment by ediazcomellas** [comment]
$100 added.

**Comment by e-alfred** [comment]
@jospoortvliet Can you add this repository to the Bountysource bot?

**Comment by jospoortvliet** [comment]
@e-alfred done. Sorry, I rarely manage to catch up to notifications in github :(

**Comment by serafin84** [comment]
Hello,
Can anyone tell me how to run this add-on or sending nextcloud attachments in the latest thunderbird?

**Comment by mxa** [comment]
Maybe someone can link the bountysource page here, I could not find it.

**Comment by tobiasKaminsky** [comment]
https://www.bountysource.com/issues/79616389-add-tb-68-support

**Comment by josepmendoza** [comment]
Onwcloud addon:
https://addons.thunderbird.net/es/thunderbird/addon/filelink-provider-for-owncloud/

Github repo:
https://github.com/thosmos/filelink-owncloud

Doesn't work with Nextcloud, but I've made a fork with a little patch that works with Nextcloud:
https://github.com/josepmendoza/filelink-owncloud

**Comment by sebastienserre** [comment]
> Doesn't work with Nextcloud, but I've made a fork with a little patch that works with Nextcloud:
> https://github.com/josepmendoza/filelink-owncloud
Could you please add a readme.md explaining how to install it without an .xpi please ?

**Comment by josepmendoza** [comment]
Installation

1. Zip all files located in the root folder such that the manifest.json in the root folder of the zip file
2. Name this zip file as filelink-owncloud@thosmos.com.xpi
3. Open your Thunderbird, and install as addon file.

or download my packed and patched addon: [filelink-owncloud-patched](https://enginy.cloud/s/YBLYDXXNw9fqs6j/download)

**Comment by sebastienserre** [comment]
Unfortunately, I have an error message "Imposible to upload to Owncloud" :-(

**Comment by manu-p** [comment]
Hi, thanks @josepmendoza 

Works fine on my side with TB68.2.2 and NC16.0.7. 
And on NC17.0.2 too.

I'm using an app token as proposed and just had to replace the storage path to the previous /Mail-attachments/ value.

**Comment by sebastienserre** [comment]
forgot to replace /Mailattachments/ on my settings to /Mail-attachments/
and it works! Thx @manu-p & @josepmendoza

**Comment by e-alfred** [comment]
@oparoz @guillaumev Can you merge the fixed code and release an official app?

**Comment by merrx** [comment]
> Onwcloud addon:
> https://addons.thunderbird.net/es/thunderbird/addon/filelink-provider-for-owncloud/
> 
> Github repo:
> https://github.com/thosmos/filelink-owncloud
> 
> Doesn't work with Nextcloud, but I've made a fork with a little patch that works with Nextcloud:
> https://github.com/josepmendoza/filelink-owncloud

The owncloud version from @thosmos didn't work with my universities owncloud, but the nextcloud version from @josepmendoza works fine. The owncloud version can upload the file, but it didn't paste anything in my mail (forever spinning indicator).

May I suggest adding some random numbers (?) to the file name as the old version did. So it doesn't make filename collisions if uploading the same file twice.

**Comment by thosmos** [comment]
> > Onwcloud addon:
> > https://addons.thunderbird.net/es/thunderbird/addon/filelink-provider-for-owncloud/
> > Github repo:
> > https://github.com/thosmos/filelink-owncloud
> > Doesn't work with Nextcloud, but I've made a fork with a little patch that works with Nextcloud:
> > https://github.com/josepmendoza/filelink-owncloud
> 
> The owncloud version from @thosmos didn't work with my universities owncloud, but the nextcloud version from @josepmendoza works fine. The owncloud version can upload the file, but it didn't paste anything in my mail (forever spinning indicator).
> 
> May I suggest adding some random numbers (?) to the file name as the old version did. So it doesn't make filename collisions if uploading the same file twice.

I've incorporated @josepmendoza's changes and also the random file name into the published version 1.7 at https://addons.thunderbird.net/es/thunderbird/addon/filelink-provider-for-owncloud/

I have it working on both owncloud and nextcloud. I would appreciate feature requests or bugs be made at its repo https://github.com/thosmos/filelink-owncloud

**Comment by wagnbeu0** [comment]
Perfect, can you share a version with the nextcloud Logos as well?

**Comment by e-alfred** [comment]
@thosmos Awesome work, but maybe @jospoortvliet @guillaumev @oparoz can add you as a collaborator to this repository? It would be good to have this in the main repository so people can simply update their extension instead of removing the "official" one and installing another one.

**Comment by thosmos** [comment]
> @thosmos Awesome work, but maybe @jospoortvliet @guillaumev @oparoz can add you as a collaborator to this repository? It would be good to have this in the main repository so people can simply update their extension instead of removing the "official" one and installing another one.

I'd be happy to contribute to this repo.  I'll see about making a PR that would modify this repo to get it to start working again.  I just added this intention to the bountysource.  That'd be fun to get some $ for this work.  ;)

**Comment by Geisterfahrer** [comment]
I really appreciate your work on getting this addon running again!

I am still missing one really cool feature from the "original" version; it is the possibility to attach Filelinks to Lightning's calendar entries. 
Is it possible to re-integrate it?

Cheers,
Michael

**Comment by jurgenhaas** [comment]
Just to let everyone know, there is another option available from https://gitlab.com/joendres/filelink-nextcloud which is working extremely well and comes with some extra features.

**Comment by e-alfred** [comment]
Anybody interested in finishing this? I (and certainly anybody who put up a bounty on Bountysource worth 130$) doesn't want to give it to Bountysource after the change in their terms of service that assigns the money to them after some time if a Bounty goes unclaimed.

I will quit their service (and shady practices) soon anyway, here is more info on that: https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943

**Comment by ediazcomellas** [comment]
As  https://gitlab.com/joendres/filelink-nextcloud  works very well, I think it is time to end this bounty and put an end to this plugin.  I would accept if someone from Nextcloud requests the bounty and gives it to nextcloud related projects. @ChristophWurst, any suggestion?

**Comment by ChristophWurst** [comment]
I would suggest [Nextcloud Include](https://nextcloud.com/include/).

But it's best if the money is donated there by someone else. As otherwise I will have to cash out *a lot* and the tax situation will be even more complex (this is not an income for me but technically this likely falls under income taxation, I'll have to check this in detail).

**Comment by e-alfred** [comment]
> As https://gitlab.com/joendres/filelink-nextcloud works very well, I think it is time to end this bounty and put an end to this plugin.

True, *cloud is the way to go. Maybe it should be the official Thunderbird extension in the future for Nextcloud?

**Comment by ediazcomellas** [comment]
> I would suggest [Nextcloud Include](https://nextcloud.com/include/).
> 
> But it's best if the money is donated there by someone else. As otherwise I will have to cash out _a lot_ and the tax situation will be even more complex (this is not an income for me but technically this likely falls under income taxation, I'll have to check this in detail).

Yes, sure... taxes can be a big player here. Maybe the Nextcloud include initiative can claim it directly to avoid all this issue. In any case, your opinion on this topic is what counts to me. Tell me how to proceed in this and the other bounties.

**Comment by ChristophWurst** [comment]
I'm in contact with KDE e.V. to figure out a way to get the money from Bountysource to the Include fund without the tax issues. I'll update the forum post with infos once I know more. Let's try to keep the info in one place :v:

**Comment by joendres** [comment]
> 
> 
> I would suggest [Nextcloud Include](https://nextcloud.com/include/).
> 
> But it's best if the money is donated there by someone else. As otherwise I will have to cash out _a lot_ and the tax situation will be even more complex (this is not an income for me but technically this likely falls under income taxation, I'll have to check this in detail).

May I humbly point out that I tried to claim the bounty when I released [*cloud](https://gitlab.com/joendres/filelink-nextcloud), but was declined by Nextcloud? I'd still be glad to take the bounty (and handle the tax issues :wink:).

I think I'll find a way to spend the money on "Refugeeks", our project to teach programming to refugees to help them to integrate via jobs in tech companies.

**Comment by joendres** [comment]
Oh, and if you really like *cloud, I'd also be very grateful for some stars on gitlab or reviews in [Thunderbird's Addon Repository](https://addons.thunderbird.net/thunderbird/addon/filelink-nextcloud-owncloud/) .

**Comment by jurgenhaas** [comment]
I second that, the *cloud plugin is awesome.

**Comment by ChristophWurst** [comment]
Sure, go ahead. I only gave a suggestion for those who don't know where to put the money. It's still your money, so your choice :wink:

**Comment by qm2k** [comment]
> Oh, and if you really like *cloud, I'd also be very grateful for some stars on gitlab or reviews in [Thunderbird's Addon Repository](https://addons.thunderbird.net/thunderbird/addon/filelink-nextcloud-owncloud/) .

Just wrote a review on Thunderbird's Addon Repository -- the extension is great, actually better then the official defunct addon was.

Would you please share the direct link on gitlab repository you'd like to have the stars on? EDIT: Oops, the [link ](https://gitlab.com/joendres/filelink-nextcloud) was in the previous message.

**Comment by joendres** [comment]
> 
> 
> Sure, go ahead. I only gave a suggestion for those who don't know where to put the money. It's still your money, so your choice 😉

Bountysource tells me, that I can claim it as soon as #80 is closed as fixed. @ChristophWurst can you do that?

**Comment by joendres** [comment]
@qm2k thanks a lot. The project ist here: https://gitlab.com/joendres/filelink-nextcloud

**Comment by ChristophWurst** [comment]
Please ask someone of the [contributors](https://github.com/nextcloud/nextcloud-filelink/graphs/contributors) to close this ticket as I do not want to get into other people's stuff.

**Comment by e-alfred** [comment]
It would be awesome to make *cloud the new official Thunderbird plugin for Nextcloud. Right now all links go to this deprecated repository leading people to a non-working extension.

**Comment by ChristophWurst** [comment]
I'm super new to this repo. I didn't even know there was a Thunderbird plugin for Nextcloud. So excuse my basic questions but is the other one a fork of this one? What is stopping you from updating the references to the new repo (on gitlab)?

**Comment by ChristophWurst** [comment]
@guillaumev @michaelletzgus @NDev8 @uli-heller would any of you have a problem with us closing this ticket so @joendres can claim the bounty?

Let's proceed with closing unless one of these four contributors raises objections. Two weeks is a reasonable time frame, I guess.

**Comment by joendres** [comment]
@ChristophWurst 
> I'm super new to this repo. I didn't even know there was a Thunderbird plugin for Nextcloud. So excuse my basic questions but is the other one a fork of this one? What is stopping you from updating the references to the new repo (on gitlab)?

No, I started from scratchbecause the current API has nothing in common with the legacy one.

**Comment by uli-heller** [comment]
closing is no problem for me

Am 24. Juni 2020, um 14:15, schrieb Christoph Wurst <notifications@github.com>:

@guillaumev @michaelletzgus @NDev8 @uli-heller would any of you have a problem with us closing this ticket so @joendres can claim the bounty?

Let's proceed with closing unless one of these four contributors raises objections. Two weeks is a reasonable time frame, I guess.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/nextcloud/nextcloud-filelink/issues/80#issuecomment-648784307">https://github.com/nextcloud/nextcloud-filelink/issues/80#issuecomment-648784307</a>", "url": "<a href="https://github.com/nextcloud/nextcloud-filelink/issues/80#issuecomment-648784307">https://github.com/nextcloud/nextcloud-filelink/issues/80#issuecomment-648784307</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by ediazcomellas** [comment]
Looks like a good solution to me.

**Comment by joendres** [comment]
@ChristophWurst it's been 3 weeks now. I'd be grateful if you could close the bug.

TIA, @joendres

**Comment by uli-heller** [comment]
I'm fine with closing but I cannot close it personally

**Comment by joendres** [comment]
> 
Sorry, I mentined the wrong person. @oparoz is the one to inform.

> @ChristophWurst it's been 3 weeks now. I'd be grateful if you could close the bug.

**Comment by joendres** [comment]
OK, I give up. None of the Contributor seems to be willing to close this issue. I had a brief contact with @oparoz via twitter, but he is unresponsive there too. I'd like to discuss _how_ to close this in a way that a) makes users happy b) makes bountysource happy. But nobody answers. So this issue will be open forever, the links from nextcloud.com will point to the disfunctional Addon, Nextcloud users might find *cloud (or not), and bountysource will put the bounty in its own pocket in the end. Whatever... 🤷‍♂️

**Comment by ediazcomellas** [comment]
How can I help?

**Comment by joendres** [comment]
I don't know, I'm just frustrated. By now I've literally spent hours to get somebody to communicate with me, who can decide and act on this project. That's more time than the bounty is worth -- just unsuccessfully trying to establish communication. Don't get me wrong: There are some people at Netxcloud, who try to be helpful. But they tell me, they can't decide. And those, they point me to, *just don't communicate*.  So I'll stop reaching out and I'll try to forget about the whole thing.

**Comment by uku69** [comment]
I am also fine with the *cloud extension. it's working without any problems. Does nobody know how to reach @oparoz for closing down this issue and force to pay out the bounties?
on the other hand - the request was opened by @johndoe7000... ?

**Comment by uli-heller** [comment]
> OK, I give up. None of the Contributor seems to be willing to close this issue. ...

The fact that you have to ask again and again is really bad. I don't know who can close the issue. But for sure, you cannot close it just because you're a contributor. Beside my name, this project says "Contributor" - probably because I proposed a pull request before - but I cannot close any issue. There is no "close issue" button. Sorry.

**Comment by ediazcomellas** [comment]
I've asked for a refund of the bounty and will send it directly to @joendres once I get it back.

**Comment by ChristophWurst** [comment]
> I don't know, I'm just frustrated. By now I've literally spent hours to get somebody to communicate with me, who can decide and act on this project. That's more time than the bounty is worth -- just unsuccessfully trying to establish communication. Don't get me wrong: There are some people at Netxcloud, who try to be helpful. But they tell me, they can't decide. And those, they point me to, _just don't communicate_. So I'll stop reaching out and I'll try to forget about the whole thing.

I'm sorry for the frustration caused. It's holiday season and some of us are simply offline for their days off, and so have I. Thus there was no communication from us.

What's left? Just closing of the ticket?

**Comment by e-alfred** [comment]
> What's left? Just closing of the ticket?

@ChristophWurst Well, all of this: 

> the links from nextcloud.com will point to the disfunctional Addon, Nextcloud users might find *cloud (or not)

*cloud is the right addon, the "official" seems to be deprecated.

**Comment by ChristophWurst** [comment]
If you give me a link we can try to find the source at https://github.com/nextcloud/nextcloud.com to change that link to the "new" addon

**Comment by ediazcomellas** [comment]
Unfortunately I retired my pledge at bountysource yesterday! I will send the bounty directly to Johannes.

**Comment by e-alfred** [comment]
@ChristophWurst I think @joendres should know but I think those are the right links:

https://addons.thunderbird.net/en-US/thunderbird/addon/filelink-nextcloud-owncloud/
https://gitlab.com/joendres/filelink-nextcloud

**Comment by ChristophWurst** [comment]
Done https://github.com/nextcloud/nextcloud.com/pull/1336
